name: Dev Builds

on:
  push:
    paths:
      - "*.gradle"
      - "gradle.properties"
      - "src/**"
      - "fabricWrapper/**"
      - "versions/**"
      - ".github/**"
  pull_request:


jobs:
  build:
    uses: ./.github/workflows/build.yml
